#!/bin/bash

i="0"

while [[ $i -lt 1 ]]
do
   #HTM Process
   (cd matlabHTM/ ; sbatch nab_parallel_script 1 16 ) &
   (cd matlabHTM/ ; sbatch nab_parallel_script 17 24 ) &
   (cd matlabHTM/ ; sbatch nab_parallel_script 25 32 ) &
   (cd matlabHTM/ ; sbatch nab_parallel_script 33 40 ) &
   (cd matlabHTM/ ; sbatch nab_parallel_script 41 45 ) &
   (cd matlabHTM/ ; sbatch nab_parallel_script 46 47 ) &
   (cd matlabHTM/ ; sbatch nab_parallel_script 48 49 ) &
   (cd matlabHTM/ ; sbatch nab_parallel_script 50 51 ) &
   (cd matlabHTM/ ; sbatch nab_parallel_script 52 53 ) &
   (cd matlabHTM/ ; sbatch nab_parallel_script 54 55 ) &
   (cd matlabHTM/ ; sbatch nab_parallel_script 56 57 ) &
   (cd matlabHTM/ ; sbatch nab_parallel_script 58 58 ) &

   # HTM+RM Process
   (cd htmau/ ; sbatch nab_parallel_script 1 16 ) &
   (cd htmau/ ; sbatch nab_parallel_script 17 24 ) &
   (cd htmau/ ; sbatch nab_parallel_script 25 32 ) &
   (cd htmau/ ; sbatch nab_parallel_script 33 40 ) &
   (cd htmau/ ; sbatch nab_parallel_script 41 45 ) &
   (cd htmau/ ; sbatch nab_parallel_script 46 47 ) &
   (cd htmau/ ; sbatch nab_parallel_script 48 49 ) &
   (cd htmau/ ; sbatch nab_parallel_script 50 51 ) &
   (cd htmau/ ; sbatch nab_parallel_script 52 53 ) &
   (cd htmau/ ; sbatch nab_parallel_script 54 55 ) &
   (cd htmau/ ; sbatch nab_parallel_script 56 57 ) &
   (cd htmau/ ; sbatch nab_parallel_script 58 58 )

   #For Script Testting Purposes
   #(cd matlabHTM/ ; bash nabScript_1-2.sh)
   #(cd htmau/ ; bash nabScript_1-2.sh)

   #sleep 30

   while [[ $(squeue -u iliabautista | grep NAB | wc -l) -gt 1 ]]
   do
      sleep 5m
      echo $i
   done

   #sleep 5s

   #matlab -nodisplay -nosplash -r "run('timing_test(1,58)')"

   i=$[$i+1]
done
