#!/bin/bash

date

for i in {1..20}
do
   for j in {1..24}
   do
      # HTM Process
      (cd matlabHTM/ ; matlab -nodisplay -nosplash -nodesktop -r "run('runNAB(80,80,false,true,$i,$j)')")

      echo "Trial Ended: $(date)"

      matlab -nodisplay -nosplash -nodesktop -r "run('dec_predicted_val(80,80,$i,$j)')"
   done
done

date

