#!/bin/bash

date

i="0"

while [[ $i -lt 1 ]]
do
   # HTM Process
   (cd matlabHTM/ ; matlab -nodisplay -nosplash -nodesktop -r "run('runNAB(80,83,false,true)')")

   # HTM+RM Process
   (cd htmau/ ; matlab -nodisplay -nosplash -nodesktop -r "run('runNAB(80,83,false,true,true,false)')")


   #For Script Testting Purposes
   #(cd matlabHTM/ ; bash nabScript_1-2.sh)
   #(cd htmau/ ; bash nabScript_1-2.sh)

#   echo "Trial Started: $(date)"

#  while [[ $(jobs | grep nohup | wc -l) -gt 0 ]]
#   do
#      sleep 5m
#      echo $i
#   done

   echo "Trial Ended: $(date)"

   matlab -nodisplay -nosplash -nodesktop -r "run('timing_test(80,83)')"

   i=$[$i+1]
done

date

